import fs from "node:fs";
import path from "node:path";
import type { Logger } from "../logger.js";

/**
 * Generate SUBSCRIPTION_GUIDE.md — the handoff document for teams building
 * AGENT-001, AGENT-002, and AGENT-004.
 */
export function buildSubscriptionGuide(dataDir: string, port: number, logger: Logger): void {
  const guide = `# Regen Market Signal Subscription Guide

Generated by AGENT-003 (RegenMarketMonitor) on ${new Date().toISOString()}.

This document describes three patterns for consuming market signals from the Market Monitor agent.

---

## Signal Schema

Every signal conforms to the \`MarketSignal\` type:

\`\`\`typescript
interface MarketSignal {
  id: string;                    // UUID v4
  version: '1.0';
  source: 'regen-market-monitor';
  agent_id: 'AGENT-003';
  signal_type: SignalType;       // PRICE_ANOMALY | PRICE_MOVEMENT | LIQUIDITY_WARNING | ...
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
  timestamp: string;             // ISO 8601
  data: SignalData;              // Discriminated union on signal_type
  context: {
    triggered_by: 'scheduled_poll' | 'event_watcher' | 'manual';
    workflow_id: string;
    poll_sequence: number;
    related_signal_ids: string[];
  };
  routing: {
    target_agents: AgentId[];    // Which agents this signal is relevant for
    broadcast_channels: string[];
    ttl_seconds: number;
    priority: 1 | 2 | 3;
  };
}
\`\`\`

Fetch the full JSON Schema at runtime: \`GET http://localhost:${port}/signals/schema\`

---

## Pattern A — Redis Streams (recommended for same-infra agents)

Each agent has a dedicated stream: \`regen:signals:AGENT-00X\`

### Subscribe to your agent's stream:

\`\`\`typescript
import Redis from 'ioredis';

const redis = new Redis(process.env.REDIS_URL);
let lastId = '$'; // Start from new messages

async function consumeSignals() {
  while (true) {
    const results = await redis.xread('COUNT', 10, 'BLOCK', 5000, 'STREAMS', 'regen:signals:AGENT-001', lastId);
    if (!results) continue;

    for (const [, messages] of results) {
      for (const [id, fields] of messages) {
        lastId = id;
        const signal = JSON.parse(fields[fields.indexOf('payload') + 1]);
        console.log(\`[\\$\\{signal.signal_type\\}] \\$\\{signal.severity\\}: \\$\\{JSON.stringify(signal.data)\\}\`);
      }
    }
  }
}
\`\`\`

### Notes:
- Stream MAXLEN is ~10,000 entries (configurable)
- Signals have a TTL in \`routing.ttl_seconds\` — discard stale signals
- Main stream: \`regen:market:signals\` contains ALL signals (all agents)

---

## Pattern B — Webhooks (for separate infrastructure)

Register your endpoint URL via the \`WEBHOOK_URLS\` env var on the Market Monitor.

### Signature Verification:

\`\`\`typescript
import crypto from 'node:crypto';
import express from 'express';

const app = express();
app.use(express.json());

app.post('/signals', (req, res) => {
  // Verify HMAC signature
  const signature = req.headers['x-signature'];
  if (signature && process.env.WEBHOOK_SECRET) {
    const expected = crypto.createHmac('sha256', process.env.WEBHOOK_SECRET)
      .update(JSON.stringify(req.body))
      .digest('hex');
    if (signature !== expected) {
      return res.status(401).json({ error: 'invalid_signature' });
    }
  }

  const signal = req.body;
  console.log(\`Received: \\$\\{signal.signal_type\\} (\\$\\{signal.severity\\})\`);

  // Process the signal...
  res.status(200).json({ received: signal.id });
});
\`\`\`

### Headers sent with every webhook:
- \`X-Signal-ID\`: UUID of the signal
- \`X-Signal-Type\`: e.g. PRICE_ANOMALY
- \`X-Signal-Severity\`: INFO | WARNING | CRITICAL
- \`X-Agent-Source\`: AGENT-003
- \`X-Timestamp\`: ISO 8601
- \`X-Signature\`: HMAC-SHA256 (if WEBHOOK_SECRET is set)

### Routing filter:
Set \`WEBHOOK_AGENT_FILTER=AGENT-001\` to only receive signals targeting AGENT-001.

---

## Pattern C — REST Polling (lightweight integrations)

### Endpoints:

\`\`\`bash
# List recent signals (with optional filters)
curl "http://localhost:${port}/signals?agent=AGENT-001&since=2024-01-01T00:00:00Z&limit=10"

# Get a specific signal by ID
curl "http://localhost:${port}/signals/<uuid>"

# Real-time Server-Sent Events stream
curl -N "http://localhost:${port}/signals/stream"

# Signal schema (JSON Schema)
curl "http://localhost:${port}/signals/schema"

# Publishing statistics
curl "http://localhost:${port}/signals/stats"
\`\`\`

### Recommended polling interval:
Match the Market Monitor's poll interval (default: 1 hour). Use the \`since\` parameter to avoid reprocessing.

---

## Signal Types and Routing

| Signal Type | Target Agents | TTL | Priority |
|---|---|---|---|
| PRICE_ANOMALY | AGENT-001, AGENT-002, AGENT-004 | 30m | 2 (WARNING) |
| PRICE_MOVEMENT | AGENT-001, AGENT-002 | 1h | 2 (WARNING) |
| LIQUIDITY_WARNING | AGENT-001, AGENT-002 | 1h | 2 (WARNING) |
| LOW_SUPPLY | AGENT-001 | 1h | 2 (WARNING) |
| GOAL_COMPLETED | AGENT-002 | 1h | 3 (INFO) |
| CURATION_DEGRADED | AGENT-001, AGENT-002 | 1h | 2 (WARNING) |
| MARKET_REPORT | AGENT-001, AGENT-002, AGENT-004 | 24h | 3 (INFO) |
| MANIPULATION_ALERT | AGENT-001, AGENT-002, AGENT-004 | 1h | 1 (CRITICAL) |
`;

  const dir = dataDir;
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, "SUBSCRIPTION_GUIDE.md");
  fs.writeFileSync(filePath, guide, "utf-8");
  logger.info({ path: filePath }, "Subscription guide written");
}
